version: '3.1'
services:
  springboot:
    image: ashokit/spring-boot-mongo
    restart: always
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
    - 8080:8080
    working_dir: /opt/app
    depends_on:
    - mongo
    networks:
    - springappnetwork
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
    - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
volumes:
  mongodb:
    external: true
networks:
  springappnetwork:
    external: true
